---
- name: Install RPM packages
  dnf:
      name:
      - freeipa-server
      - fedora-messaging
      - gcc
      - git
      - poetry
      - python3-cryptography
      - python3-devel
      - python3-flask
      - python3-pip
      - vim
      state: present

- name: Check if noggin is cloned already
  become_user: vagrant
  stat: path=noggin
  register: noggin_dir

- name: Clone noggin repository
  become_user: vagrant
  command: git clone https://github.com/fedora-infra/noggin.git
  when: not (noggin_dir.stat.exists and noggin_dir.stat.isdir)

- name: install python deps with poetry
  become_user: vagrant
  command:
    cmd: poetry install
    chdir: noggin

- name: Install the bashrc
  copy:
    src: .bashrc
    dest: /etc/profile.d/vagrant-noggin.sh
    mode: 0644
    owner: root
    group: root

- name: Install noggin.cfg
  become_user: vagrant
  template:
    src: noggin.cfg
    dest: noggin.cfg

- name: compile the translations
  become_user: vagrant
  command:
    cmd: poetry run pybabel compile -d /home/vagrant/noggin/noggin/translations
    chdir: noggin

- name: Install the systemd unit files for noggin services
  copy:
    src: noggin.service
    dest: /etc/systemd/system/noggin.service
    mode: 0644

- name: Start noggin service using systemd
  systemd:
    state: started
    name: noggin
    daemon_reload: yes
    enabled: yes
