---
- name: add fmn vhost
  rabbitmq_vhost:
    name: /fmn
    state: present

- name: Create a fedoramessages user in RabbitMQ
  rabbitmq_user:
    user: fedoramessages
    password: fedoramessages
    tags: administrator
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
  notify:
    - reload rabbitmq

- name: update permissions for the fmn vhost
  rabbitmq_user:
    user: fedoramessages
    password: fedoramessages
    tags: administrator
    vhost: /fmn
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
  notify:
    - reload rabbitmq

# fedora-messaging-logger is a simple service that logs all messages to journal
# so you can go back and easily see all messages sent here
- name: Install the systemd unit files for the fedora-messaging-logger service
  copy:
      src: fedora-messaging-logger.service
      dest: /etc/systemd/system/fedora-messaging-logger.service
      mode: 0644

- name: Start fedora-messaging-logger service using systemd
  systemd:
    state: started
    name: fedora-messaging-logger
    daemon_reload: yes
    enabled: yes

- name: Install the .bashrc
  copy:
      src: bashrc
      dest: /home/vagrant/.bashrc
      mode: 0644
      owner: vagrant
      group: vagrant
