---
# limnoria depends on python3-mock which is in powertools
- name: Enable CentOS Powertools
  ini_file:
    path: /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
    section: powertools
    option: enabled
    value: "1"

# enable epel testing
- name: Enable EPEL updates-testing
  ini_file:
    path: /etc/yum.repos.d/epel-testing.repo
    section: epel-testing
    option: enabled
    value: "1"

# https://kojipkgs.fedoraproject.org//work/tasks/6262/68326262/python3-sgmllib3k-1.0.0-2.el8.noarch.rpm
- name: Install RPM packages
  dnf:
      name: ['limnoria', 'supybot-fedora', 'python3-sgmllib3k', 'supybot-koji', 'supybot-meetbot', 'supybot-notify', 'ngircd', 'weechat', 'git', 'vim', 'krb5-workstation', 'krb5-devel', 'gcc']
      disable_gpg_check: yes
      state: present

- name: set ngircd config
  copy:
      src: ngircd.conf
      dest: /etc/ngircd.conf

- name: Start ngircd service using systemd
  systemd:
    state: started
    name: ngircd
    daemon_reload: yes
    enabled: yes

#- name: install python deps with poetry
#  shell: poetry install
#  become: yes
#  become_user: vagrant
#  args:
#    chdir: /vagrant/

- name: kinit for nonbot
  shell: echo "{{ipa_admin_password}}" | kinit {{ ipa_admin_user }}@{{ krb_realm }}

- name: copy supybot config
  copy:
      src: supybot
      dest: /home/vagrant
      owner: vagrant
      group: vagrant

- name: Install the systemd unit files for the nonbot service
  copy:
      src: nonbot.service
      dest: /etc/systemd/system/nonbot.service
      mode: 0644

- name: Start nonbot service using systemd
  systemd:
    state: started
    name: nonbot
    daemon_reload: yes
    enabled: yes

- name: Install the bashrc
  copy:
      src: .bashrc
      dest: /etc/profile.d/vagrant-nonbot.sh
      mode: 0644
      owner: root
      group: root
