---
- name: Install IPA client packages
  package:
    name:
      - freeipa-client
    state: present
  tags:
    - ipa/client
    - packages

- name: Basic configuration for client on IPA cluster
  delegate_to: freeipa
  import_tasks: common.yml
  tags:
    - ipa/client
    - config

- name: Configure HBAC on IPA cluster
  delegate_to: freeipa
  import_tasks: hbac.yml
  tags:
    - ipa/client
    - config

- name: Configure sudo via IPA
  delegate_to: freeipa
  import_tasks: sudo.yml
  tags:
    - ipa/client
    - config
