---
- name: Install RPM packages
  dnf:
    name:
      - python
      - git
      - gcc
      - python-devel
      - krb5-devel
      - libpq-devel
    state: present

- name: Install the .bashrc
  copy:
    src: .bashrc
    dest: /home/vagrant/.bashrc
    mode: 0644
    owner: vagrant
    group: vagrant

- name: get fedora-electionss
  git:
    repo: https://pagure.io/elections.git
    dest: /home/vagrant/elections

- name: install elections requirements
  pip:
    requirements: /home/vagrant/elections/requirements.txt

- name: copy the config file
  copy:
    src: config
    dest: /home/vagrant/elections/config
    mode: 0644
    owner: vagrant
    group: vagrant

- name: Install the systemd unit files for election services
  copy:
      src: "{{ item }}"
      dest: /etc/systemd/system/{{ item }}
      mode: 0644
  with_items:
      - elections.service

- name: set default client keytab in krb5.conf
  lineinfile:
    path: /etc/krb5.conf
    insertafter: 'default_ccache_name.*'
    line: '  default_client_keytab_name = FILE:/etc/krb5.keytab'

- name: create the database
  shell: python createdb.py
  environment:
    FEDORA_ELECTIONS_CONFIG: /home/vagrant/elections/config
  args:
    chdir: /home/vagrant/elections

- name: Start elections service using systemd
  systemd:
    state: started
    name: elections
    daemon_reload: yes
    enabled: yes
