---
- hosts: auth
  become: true
  become_method: sudo
  roles:
    - common
    - role: freeipa
      tags: ipa
    - role: ipsilon
      tags: ipsilon
    - role: noggin
      tags: noggin
    - role: fasjson
      tags: fasjson
    - role: oidc-register
      tags: oidc-register
      vars:
        ipsilon_hostname: "{{ ansible_fqdn }}"
        redirect_path: test-auth/oidc/oidc_callback
        dest: "/home/vagrant/test-auth.client_secrets.json"
    - role: test-auth
      tags: test-auth

  handlers:
    - name: restart httpd
      systemd:
        name: httpd
        state: restarted
        daemon_reload: yes

    - name: restart gssproxy
      systemd:
        name: gssproxy
        state: restarted
        daemon_reload: yes
