- name: Install RPM packages
  dnf:
    name:
      - python3-devel
      - python3-pip
      - python3-setuptools
      - python3-flask
      - python3-gunicorn
      - git
    state: present

- name: Install the bashrc
  copy:
    src: bashrc
    dest: /etc/profile.d/vagrant-test-auth.sh
    mode: 0644
    owner: vagrant
    group: vagrant

- name: Clone repository
  become_user: vagrant
  git:
    repo: https://github.com/abompard/test-auth.git
    dest: /home/vagrant/test-auth
  notify:
    - restart test-auth

- name: Install the app
  command:
    cmd: python3 setup.py install
    chdir: /home/vagrant/test-auth
    creates: /usr/local/lib/python{{ py3ver }}/site-packages/fedora_test_auth-0.0.1-py{{ py3ver }}.egg
  notify:
    - restart test-auth

- name: Copy the config file
  copy:
    src: config.py
    dest: /home/vagrant/config.py
    mode: 0644
    owner: vagrant
    group: vagrant
  notify:
    - restart test-auth

- name: Install the systemd unit
  copy:
      src: app.service
      dest: /etc/systemd/system/test-auth.service
      mode: 0644
  notify:
    - restart test-auth

- name: Start service using systemd
  systemd:
    state: started
    name: test-auth
    daemon_reload: yes
    enabled: yes
