---
- name: Create the virtual host in IPA
  shell: ipa host-add {{ vhost }} --force
  register: result
  changed_when: '"Added host" in result.stdout'
  failed_when: '" already exists" not in result.stderr and result.rc != 0'

- name: Allow the host to manage the virtual host
  shell: ipa host-add-managedby --hosts={{ ansible_fqdn }} {{ vhost }}
  register: result
  changed_when: '"Number of members added 1" in result.stdout'
  failed_when: '(ansible_fqdn + ": This entry is already a member") not in result.stdout and result.rc != 0'

- name: Get the keytab
  import_role:
    name: ipa-keytab
  vars:
    krb_service: HTTP
    krb_host_fqdn: "{{ vhost }}"
    keytab_path: /etc/httpd/conf/{{ app_name }}.keytab
    keytab_owner: apache
    keytab_group: apache

- name: Create the SSL certificate
  import_role:
    name: cert
  vars:
    cert_hostname: "{{ vhost }}"
    cert_basename: "{{ app_name }}"
